---
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Install Phase"
  pre_build:
    commands:
      - pip3 install ansible
      - pip3 install pypsrp
      - echo "Installing Packer..."
      - cd $CODEBUILD_SRC_DIR
      - cd /usr/local/bin/ && curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.6.0/packer_1.6.0_linux_amd64.zip && unzip packer.zip
      - cd $CODEBUILD_SRC_DIR/imagepipeline
      - echo "Validating packer JSON"
      - packer validate windows_2019.json
      - echo $HOME
  build:
    commands:
      - echo "Build Phase"
      - cd $CODEBUILD_SRC_DIR/imagepipeline
      - packer build -color=false windows_2019.json

artifacts:
  files:
    - build.log
  discard-paths: yes
